---
# ==============================================================================
# File: ansible/roles/technitium_dns/handlers/main.yml
# Purpose:
#   Handlers for the Technitium DNS role.
# ==============================================================================

- name: Reload ufw
  ansible.builtin.command: ufw reload
  changed_when: false

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
